apiVersion: v1
kind: ConfigMap
metadata:
  name: arm2-configmap
  namespace: deviceshifu
  labels:
    app: deviceshifu-arm2
    workspace_id: "d6f82feb-3c2d-425f-9b3a-b9dec0d745e2"
    workspace_name: "rawang"
data:
  driverProperties: |
    driverSku: Robot Arm Controller
    driverImage: deviceshifu-robot-arm:v0.0.5
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-arm2
  namespace: devices
  labels:
    app: deviceshifu-arm2
    workspace_id: "d6f82feb-3c2d-425f-9b3a-b9dec0d745e2"
    workspace_name: "rawang"
  annotations:
    workspace.id: "d6f82feb-3c2d-425f-9b3a-b9dec0d745e2"
    workspace.name: "rawang"
    template.id: "robot-arm-v1"
spec:
  sku: "Robot Arm Controller"
  connection: Ethernet
  address: "192.168.58.2"
  protocol: RPC
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deviceshifu-arm2
  namespace: deviceshifu
  labels:
    app: deviceshifu-arm2
    workspace_id: "d6f82feb-3c2d-425f-9b3a-b9dec0d745e2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-arm2
  template:
    metadata:
      labels:
        app: deviceshifu-arm2
        workspace_id: "d6f82feb-3c2d-425f-9b3a-b9dec0d745e2"
    spec:
      containers:
        - name: robot-arm-controller
          image: registry.test.shifu.dev/edgenesis/deviceshifu-robot-arm:v0.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NATS_SERVER
              value: "nats://broker.test.edgenesis.net:4222"
            - name: JOYSTICK_TOPIC
              value: "rawang.arm2"
            - name: EDGEDEVICE_NAME
              value: "edgedevice-arm2"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
            - name: JOG_SPEED
              value: "20"
            - name: CONTROL_LOOP_HZ
              value: "5"
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
      serviceAccountName: edgedevice-sa
      volumes:
        - name: deviceshifu-config
          configMap:
            name: arm2-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: deviceshifu-arm2
  namespace: deviceshifu
  labels:
    app: deviceshifu-arm2
    workspace_id: "d6f82feb-3c2d-425f-9b3a-b9dec0d745e2"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: deviceshifu-arm2
  type: ClusterIP
