apiVersion: v1
kind: ConfigMap
metadata:
  name: cam-01-configmap
  namespace: deviceshifu
  annotations:
    workspace.id: "66e118f0-c694-49fc-9d1e-0b1b47a67661"
    workspace.name: "bit"
data:
  driverProperties: |
    driverSku: HTTP USB Camera Device
    driverImage: edgenesis/usb-camera:v0.0.1
  instructions: |
    instructions:
      video:
      capture:
      probe:
  telemetries: |
    telemetries:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-cam-01
    workspace.id: "66e118f0-c694-49fc-9d1e-0b1b47a67661"
    workspace.name: "bit"
  name: deviceshifu-cam-01
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-cam-01
  template:
    metadata:
      labels:
        app: deviceshifu-cam-01
        workspace.id: "66e118f0-c694-49fc-9d1e-0b1b47a67661"
        workspace.name: "bit"
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:nightly
          name: deviceshifu-cam-01
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-cam-01"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
        - image: edgenesis/usb-camera:v0.0.3
          securityContext:
            privileged: true
          name: camera-python
          env:
            - name: CAMERA_WIDTH
              value: "640"
            - name: CAMERA_HEIGHT
              value: "480"
            - name: VIDEONUMBER
              value: "0"
          volumeMounts:
            - name: video
              mountPath: "/dev"
          resources:
      volumes:
        - name: deviceshifu-config
          configMap:
            name: cam-01-configmap
        - name: video
          hostPath:
            path: /dev
      serviceAccountName: edgedevice-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-cam-01
    workspace.id: "66e118f0-c694-49fc-9d1e-0b1b47a67661"
    workspace.name: "bit"
  name: deviceshifu-cam-01
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-cam-01
  type: ClusterIP
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-cam-01
  namespace: devices
  annotations:
    workspace.id: "66e118f0-c694-49fc-9d1e-0b1b47a67661"
    workspace.name: "bit"
spec:
  sku: "HTTP USB Camera Device"
  connection: Ethernet
  address: 0.0.0.0:5001
  protocol: HTTP
