apiVersion: v1
kind: ConfigMap
metadata:
  name: therometer-01-configmap
  namespace: deviceshifu
  annotations:
    workspace.id: "1b5034e7-11ad-4bda-b41d-32fc3bd51ac1"
    workspace.name: "Factory01"
data:
  driverProperties: |
    driverSku: opcua-led-light-v1
    driverImage: 
  instructions: |
    instructions:
      "number":
        protocolPropertyList:
          OPCUANodeID: "ns=1;s=number"
      "light":
        protocolPropertyList:
          OPCUANodeID: "ns=1;s=light"
  telemetries: |
    telemetries:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-therometer-01
    workspace.id: "1b5034e7-11ad-4bda-b41d-32fc3bd51ac1"
    workspace.name: "Factory01"
  name: deviceshifu-therometer-01
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-therometer-01
  template:
    metadata:
      labels:
        app: deviceshifu-therometer-01
        workspace.id: "1b5034e7-11ad-4bda-b41d-32fc3bd51ac1"
        workspace.name: "Factory01"
    spec:
      containers:
        - image: edgehub/deviceshifu-http-opcua:v0.64.0
          name: deviceshifu-therometer-01
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-therometer-01"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: therometer-01-configmap
      serviceAccountName: edgedevice-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-therometer-01
    workspace.id: "1b5034e7-11ad-4bda-b41d-32fc3bd51ac1"
    workspace.name: "Factory01"
  name: deviceshifu-therometer-01
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-therometer-01
  type: LoadBalancer
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-therometer-01
  namespace: devices
  annotations:
    workspace.id: "1b5034e7-11ad-4bda-b41d-32fc3bd51ac1"
    workspace.name: "Factory01"
spec:
  sku: "OPC UA LED Light"
  connection: Ethernet
  address: "192.168.0.80:10123"
  protocol: "OPCUA"
  protocolSettings:
    OPCUASetting:
      AuthenticationMode: Anonymous
