apiVersion: v1
kind: ConfigMap
metadata:
  name: usb-camera-01-configmap
  namespace: deviceshifu
  annotations:
    workspace.id: "1b5034e7-11ad-4bda-b41d-32fc3bd51ac1"
    workspace.name: "Factory01"
data:
  driverProperties: |
    driverSku: HTTP USB Camera Device
    driverImage: edgenesis/usb-camera:v0.0.1
  instructions: |
    instructions:
      video:
      capture:
      probe:
  telemetries: |
    telemetries:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-usb-camera-01
    workspace.id: "1b5034e7-11ad-4bda-b41d-32fc3bd51ac1"
    workspace.name: "Factory01"
  name: deviceshifu-usb-camera-01
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-usb-camera-01
  template:
    metadata:
      labels:
        app: deviceshifu-usb-camera-01
        workspace.id: "1b5034e7-11ad-4bda-b41d-32fc3bd51ac1"
        workspace.name: "Factory01"
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:nightly
          name: deviceshifu-usb-camera-01
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-usb-camera-01"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
        - image: edgenesis/usb-camera:v0.0.2
          securityContext:
            privileged: true
          name: camera-python
          env:
            - name: VIDEONUMBER
              value: "0"
          volumeMounts:
            - name: video
              mountPath: "/dev"
          resources:
      volumes:
        - name: deviceshifu-config
          configMap:
            name: usb-camera-01-configmap
        - name: video
          hostPath:
            path: /dev
      serviceAccountName: edgedevice-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-usb-camera-01
    workspace.id: "1b5034e7-11ad-4bda-b41d-32fc3bd51ac1"
    workspace.name: "Factory01"
  name: deviceshifu-usb-camera-01
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-usb-camera-01
  type: ClusterIP
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-usb-camera-01
  namespace: devices
  annotations:
    workspace.id: "1b5034e7-11ad-4bda-b41d-32fc3bd51ac1"
    workspace.name: "Factory01"
spec:
  sku: "HTTP USB Camera Device"
  connection: Ethernet
  address: 0.0.0.0:5001
  protocol: HTTP
